import csv
from datetime import datetime, timedelta, time, timezone as dt_timezone
from django.http import HttpResponse
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from inventory.models import OrderTransaction, OrderItem
from pytz import timezone as pytz_timezone


@login_required(login_url='/user/login/')
def export_orders_to_csv(request, time_period='daily'):
    kampala_tz = pytz_timezone('Africa/Kampala')
    now_kampala = timezone.now().astimezone(kampala_tz)

    # Determine business day: If before 10AM, business day is yesterday
    if now_kampala.time() < time(10, 0):
        business_day = now_kampala.date() - timedelta(days=1)
    else:
        business_day = now_kampala.date()

    if time_period == 'daily':
        start_local = datetime.combine(business_day, time(10, 0, 0))
        end_local = datetime.combine(
            business_day + timedelta(days=1), time(9, 59, 59))

        start_aware = kampala_tz.localize(
            start_local).astimezone(dt_timezone.utc)
        end_aware = kampala_tz.localize(end_local).astimezone(dt_timezone.utc)

        date_str = business_day.strftime('%Y-%m-%d')
        next_day_str = (business_day + timedelta(days=1)).strftime('%Y-%m-%d')
        filename = f'orders_{date_str}_10AM_to_{next_day_str}_9AM.csv'
        heading = f'ORDERS REPORT ({date_str} 10:00AM to {next_day_str} 9:00AM)'
    else:
        today = timezone.localdate()
        if time_period == 'weekly':
            start_date = today - timedelta(days=today.weekday())
            heading = 'WEEKLY ORDERS REPORT'
            filename = 'order_items_this_week.csv'
        elif time_period == 'monthly':
            start_date = today.replace(day=1)
            heading = 'MONTHLY ORDERS REPORT'
            filename = 'order_items_this_month.csv'
        elif time_period == 'biannual':
            start_date = today.replace(
                month=((today.month - 1) // 6) * 6 + 1, day=1)
            heading = 'BIANNUAL ORDERS REPORT'
            filename = 'order_items_this_biannual.csv'
        elif time_period == 'annual':
            start_date = today.replace(month=1, day=1)
            heading = 'ANNUAL ORDERS REPORT'
            filename = 'order_items_this_year.csv'
        else:
            return HttpResponse("Invalid time period", status=400)

        start_local = datetime.combine(start_date, datetime.min.time())
        end_local = datetime.combine(
            today + timedelta(days=1), datetime.min.time())

        start_aware = kampala_tz.localize(
            start_local).astimezone(dt_timezone.utc)
        end_aware = kampala_tz.localize(end_local).astimezone(dt_timezone.utc)

    # Prepare response
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = f'attachment; filename="{filename}"'
    writer = csv.writer(response)

    # Report heading
    writer.writerow([heading])
    writer.writerow([])

    # Headers
    column_headers = [
        'ORDER DATE', 'ORDER TIME', 'TRANSACTION ID',
        'CATEGORY', 'MENU ITEM', 'QUANTITY',
        'UNIT PRICE', 'TOTAL PRICE', 'PAYMENT MODE',
        'SERVED BY', 'GENERATED BY', 'CUSTOMER NAME'
    ]
    writer.writerow(column_headers)

    # Fetch transactions
    order_transactions = OrderTransaction.objects.select_related(
        'dining_area', 'table', 'created_by'
    ).filter(
        created__gte=start_aware,
        created__lt=end_aware,
        payment_mode__in=["CASH", "MOMO PAY", "BANK CARD", "AIRTEL PAY"]
    )

    total_sum = 0
    record_count = 0

    for order in order_transactions:
        order_items = OrderItem.objects.select_related(
            'menu_item__category').filter(order=order)
        for item in order_items:
            category_name = item.menu_item.category.name if item.menu_item and item.menu_item.category else 'N/A'
            order_date_local = timezone.localtime(item.order_date, kampala_tz)
            writer.writerow([
                order_date_local.strftime('%Y-%m-%d'),
                order_date_local.strftime('%H:%M:%S'),
                order.random_id,
                category_name,
                item.menu_item.name if item.menu_item else 'N/A',
                item.quantity,
                float(item.menu_item.price) if item.menu_item else 0,
                float(item.total_price),
                order.payment_mode,
                order.served_by,
                order.created_by.username if order.created_by else 'Unknown',
                order.customer_name,
            ])
            total_sum += float(item.total_price)
            record_count += 1

    # Summary
    writer.writerow([])
    writer.writerow(['SUMMARY'])
    writer.writerow([f'Total Records: {record_count}'])
    writer.writerow([f'Total Amount: Ugx {total_sum:,.2f}'])

    return response
